name: Deploy

on:
  push:
    branches:
    - master
    - main

jobs:
  ci:
    name: Deploy to Buckets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gettext package
        run: sudo apt-get install -y s3cmd

      - name: Deploy to all environments
        run: ./deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
